#!/usr/bin/env bash

# Go to the project directory first
cd /media/shared/proj || {
    echo "Failed to change directory to /media/shared/proj"
    exit 1
}

# SSH into AWS using your key
ssh -i "ceg2350-aws-vm.pem" ubuntu@3.231.254.200
